name: SinCOM
favicon: null
layout_spectrum: 0.7895330025348812
typography_spectrum: 0.1749136126600206
title: SinCOM LLC - Sport Management Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72763675-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3779661632142961
  lightness: 0.5156013907399029
  saturation: 0.5633651097305119
  rhythmicContrast: 0.32039554859511554
purpose: []
